export const CART_ITEM_TYPES = {
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  CLEAR_CART: "CLEAR_CART"
}

export const USER_TYPES = {
  USER_SIGNUP: "USER_SIGNUP",
  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",
  USER_LOADING: "USER_LOADING",
  USER_AUTH_START: "USER_AUTH_START",
  USER_AUTH_SUCCESS: "USER_AUTH_SUCCESS",
  USER_AUTH_ERROR: "USER_AUTH_ERROR",
  CLEAR_AUTH_ERROR: "CLEAR_AUTH_ERROR"
}